######################################################################
# Automatically generated by qmake (1.07a) Tue May 18 00:24:27 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += naming_widgets.cpp
