######################################################################
# Automatically generated by qmake (1.07a) Mon May 17 23:50:12 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += button.cpp
