######################################################################
# Automatically generated by qmake (1.07a) Mon May 17 23:21:14 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += hello-world.cpp
