bootstrap:
	cp $(PWD)/src/parts/fifth-iteration/0-main-window-working.rs $(PWD)/src/main.rs

first:
	cp $(PWD)/src/parts/fifth-iteration/1-main-window-and-objects-printed.rs $(PWD)/src/main.rs

second:
	cp $(PWD)/src/parts/fifth-iteration/2-implemented-from-position-to-rect.rs $(PWD)/src/main.rs

third:
	cp $(PWD)/src/parts/fifth-iteration/3-add-gameover-and-constants.rs $(PWD)/src/main.rs

fourth:
	cp $(PWD)/src/parts/fifth-iteration/4-fast-snake.rs $(PWD)/src/main.rs

fifth:
	cp $(PWD)/src/parts/fifth-iteration/5-moving-snake-no-control.rs $(PWD)/src/main.rs

sixth:
	cp $(PWD)/src/parts/fifth-iteration/6-controlling-snake.rs $(PWD)/src/main.rs

seventh:
	cp $(PWD)/src/parts/fifth-iteration/7-window-bounds.rs $(PWD)/src/main.rs

eighth:
	cp $(PWD)/src/parts/fifth-iteration/8-snake-body.rs $(PWD)/src/main.rs

ninth:
	cp $(PWD)/src/parts/fifth-iteration/9-fruit-collision.rs $(PWD)/src/main.rs

tenth:
	cp $(PWD)/src/parts/fifth-iteration/10-random-fruit-generation.rs $(PWD)/src/main.rs

eleventh:
	cp $(PWD)/src/parts/fifth-iteration/11-self-collision-working.rs $(PWD)/src/main.rs

twelveth:
	cp $(PWD)/src/parts/fifth-iteration/12-initial-direction-fixed.rs $(PWD)/src/main.rs

thegame:
	@echo "You have to do it, bro!"
