######################################################################
# Automatically generated by qmake (1.07a) Tue May 18 01:17:25 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += encapsulating_widgets.cpp
