######################################################################
# Automatically generated by qmake (1.07a) Tue May 18 00:50:04 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += connecting_widgets.cpp
