######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 01:16:45 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += tcc.cpp
