require "#{File.expand_path(File.dirname(__FILE__))}/programming_test"

textA  = "cstfcg tscsmtvb kvk chcdx ncjkvcr tzrwnhr ntk dcw qzlvt mdffwvp nrv zvbc hpdczszh mrmfdlmq wlhszdnr zqg ttvm xmnhbhsm nmgn whw dqwk zmclgfxv pwfkscnd fzjqbs wdktct zcmtn hkxg zlgjdq dknpjn rkdh kckvqw tskszbt tlnsp dhvh tcgc pfgfp twqqqd dtdmqvt xqm fvdxj xxrtp lrdb mwmb kppg zngkwr gvr qfhkk hxbdddv bnqktj ptc lvdzshr qzjgt bjh khdqpcpc bhdgdq sjr gft dxnhz tvz kwv lllsdzxz dvnfhvc tfzxprd qfgk rqnxbpzh xgzq lfffd txds swmrvnx wpztnhsx dbvknjcw bsd zkhlpqd bdgsmldn qvxnzbh zxfwr lkqsgjv pfk pjqrbt jkq wdnqjwx jtgztncn mqnbq zfq zrwvjd sdw fgx hmzqg nzdstfm gwjncm kmwbztr rprqvz pczbnrb jjsbnjwv lnfhs wglncbbb xcvckzwp hhzkkxlz bfgzdmmq msgvqccf fjd gzbmzm lwmzfm hnq tfrckj glt scjfhwv dgfjzkx hlmjqq ngdvgld sqrcsdhh gjprqp nrpjcjxz xdln vhhnnn pqwl frrfsj xhntp nqm kvgm rcxkq pmpwrknv xmjf vwxl wfgwbzn csnbzclx czdh kbknrkc lxvbln ksrgdc jzdpnx tznk dqj wblm bbhd dfmsg rdn fqdz vrwrrvl hzp mklzsj nrgzpccf lxrbzhp lmblbcdm mkkwd vrfhsf zmtjffgn tnhlwtlk qdcz ftpbll dxtqsld dzrmjsph jgch "
textA += "hvvw krjjdd dcnppgx ftmrnzp ktjvng tcwwz prfvvqfb hsdpgnb lvwsntc qxnlbpdj hshzd rmkwz qhq jwq wwbflk nbwpgh pfvjxzcm rvn rvkwbz cqwqj ngkg wdvqv xbcskzs fpr nfsznq gcxjb qbp vbsslcmw qzkxvrv fmm dgfm mtlzj jzkzpg nvsz ndxhx mrg pdhgtl vhzklhbj fxdfxx bjqmkwk svkfhwm sthnmkpk vntcwtw rxjjzzn ncglsrz nwkbn hqfjmwsv mdfvxq wbmlz tzqjt hsxffbbz xlq pwbprr jktl nqrkdc mdtl zqzzzhbt stctrw skrr gzpzq nzsqtstd pwqx sjwzfpq xjkpqhnn qkskq hdjxt rxrzdfd bcmcxz lkb pxbqbpr vwg nrcxngj sjjhh ltznmgz nvqn zkb zxvdzrf xrvhpphv nbfcft npqlm rcdvb vhh npzq pzfhrwlw rpg xsdbm wtcgnb dmfwcjgt pqtlxxr tjp hrskr kkchnphv vczlt zxrfd pbk zbzndd vzsbtwdz vrcxw fgbqpb lnhsvg qgjktk ctzp vwhmwm dfndbzd kwpv qsfc bspkv rlmwh xsqw mgsnsrt vkjsrq tnsrz fckpt vddn zncmtl fsd cgljjxh bwrr ffkkbmnb vslqfqff xbqxdsh xgnblmqx sjmqdcr mzvzjlr btlt cpq tggbxwr xnr cbb jbp bpbrssw jnxxsrx ctxm dwlx jvrcckvh klxk rzjj wqwbsl dhgq zsmfkjh kfpjds gvhr tzxnvw krzvsdr bws fnmgpcf skgc qjq xxdsrd lntsk gmcklkq tmfns wbv mhgxpzb tvfz rdzqzmht fxjnh wlrvscv spvmb gjjlfh jtttmh ddjcpdhz lql wmmmhqv nhdtrh hwjnhnv rlmljhcl jtrmdcx ldckff zznnvp zsmkfhdh bjpzxclw hrbv dhrdrqj vdvlblzl zjd lsclbdls tckmc pkkn ngjccpp gwqf wlnl drpks psffpzng jlpd lbkxbr lcmxr ztvgjzq xdhrhwbb qmlkswmr cfk fldtn bqm hbxtgl ltg vlblzc ppzxxmnb gtk whxsnzbj pkvgdfg mlnbtth mwbtmfc cbr pxvthgjv mfkgbkm mvqvd lbnxmnpp rltcthd xjfb xwwgfr msb bkx wzqdf wfksv hcn qgftdcqh wdwktskm vvwf wchfj dnngkdz thxtd tkrnnkx rfwmmtl hdxd vtwtwxsz njpq jbmlkkdz rdjr rfj rkhfn lnv xntzf jwthqdwc hdkstn vpjzxn jcm vhnwvljl bblbpcnd zpphr bkwhb jxgjktsj fnlqm sbwtfgqw ttqchfvj lnxwzz bxcsmw kgk kdf nvcqrb trfdhwqr xnlxcmts whskss khzwzbrd pggdq vhqvm gjjh jhhsz djdzk pbzznsw wshjp lnl rzpm qjphxcqb jnhbwzpj xlrh pntzljq lxgzrqfz wbc wlt zzjltrvp glv lzvcht pvtqlvqx xldw tzgndw vptx wcxtrbm lpptfgdb vmmjzw dtk lbzph wvjj jlc jgl bhllmwj kfgd qpm lzttdtcj lgssc vnkbt dsgq wkk hrqztzgl kdfvsh btrcblts szlv ztsvm hwcjchc wjjkczdp kfzht zltggz wvnvzdv fshqtz jnntcf zglbkhl ngn fpz qxlr vrtsvr wwws shrwkd mdnjf mskdk tmb pnlxwqg wwjgnz wgd jdp kxxpxl zhjtqzb ztr dtqws ljlx hpr tksllfz fvdl jsfnnnft wtfwr svmqhlff qsnx nkmbznhn hsmmk wwsvbzs nkfw ckp bswx kjknwg csr bjwfsjg zscjsh mcbqs kcmbfmhf kbzfr dgp jwrd fvhdmcrf snpp jfbg flxpgswh rjfpzlfl dkxgkgfc smffkkr fhldf qkf bhpr ndmmbs brzl jctfdx ncqmd mkm gvtng btfvd vpks hzbjmmc ssg xmj wppsmsv vwmf rsjbkb zkrl qwzwhck xqpnh djczj kwm vmrcccm zrq nvvt bngbsbpw hdhcz bbmxj vrl wkppxt ckdxxh pmtlb nbqwdqj vkqggrtx mwh vswfth ghxr qtll jpzhk rxnrrfm brvz mbcfds fjgqf jfhzgx qjxssg wjjg cxsfftgq bbgtb qvt vlz fzq gzklssj vvsmcv tjvb wdvr gqzhfq wmw fskmh zmlq hlz gbvjv hwsf xgtmf vfl xcjg hqgrwkdz tzllrc hmlxgt mxjmf qvklmqg rpbqvg cjfcml dwq dqwqwb tjsj vghf sbbfwx dxvvk xlv cvhgs qlmcvmw hnzf njrlnvt qwqzg mlnj tvnxb hrpctkk hrsnczbl hpstfjb qhtgxsbd dwgv gczfcjh wbhfngw mspgkbt qtsqrb"

textB  = "whx fscqfd tjk nngmfc crnm cblnnljq ztgrd thdw hzqcg nhfdnqc gmhccf vjjlqfc zdl hkhqc jxkmcfc gkzzwfcs ztpwg xrdj xlct szhkckk vwrhjs lpprc lwppfnl zmvl vtkv klz tgsgvrx xvdl fll vvcfwk pjrntdt wgzpgvvf qxnvkpxd cmxpmrw jmrhr swqjnw xpc zdx bhlmrx plf kzgrmzdm jmqptsx qqmrlppj tcdblnq sdl dxhhp mpjm rnxbjsm pck wxlrsvk nsrjf fmgjvpc mcbqq vqw mpcrgz gmlnwjn ldnqbddb scklb lgn ffdwdx bmslpqzn mllbtx plvsvqnt dpllw wkjd zvbc hjxl gnzwss cwvsmx nklnlm snbqm gwncqf xvnpcb sxkx jjfgsgmb xqllpj dxcqsngf stpfnmnd hthm nrdjb kzxknjw pzq stgmhpnh csds pnjd znxrxc dxkd hnqjzc qpfr wfm drbmg lwn kml tzh dkc fwtzd hpflhqh vwtnpxb xbmhp pjqt pxfk qzkvg qjqkrzdk lhkzz dpc xxzmlpl src jtczsqj shvrxcrk fqmz fkdvmgw mhchj jxhzfkm fts jkdc npvdgpf jcvnpxs wschf xpx qtwcnw mtqjnbjs flrc pdfcjzks vggfswb mkmvllh nnzxrl kwcnrxk zgqtvnps lpmkk wngqf vgt rxbtf sxn pbdtdxr gkfgkrx mjvdk jsvm vglgf pbzgqccx dqzj cfwvtd nttwhj nkz hbvn pjxlddkr kwz bmzmbvbw jsstkxc jxvjw jskz dvprzm kknfpwbc zkm xbrhlnk dgqxmb "
textB += "nfwbmw nbpkwmsp jnrhrv bwdj kvc zpw nkgzfnmn wnwj dhv dnvjthr wsgcvl shqpw gndz lhncpbxn tjsgnl sgblg wjkkdp sdng qhtthqt frtch spfdkxh rkfmd dpwvtmm vnrb dkjr cgzd qwcbmqz swxksss wgqrdd ptvmvmlj xmnrpbj vpgf gkssm mvvjhlf rfpvdb rbtsf pgjp ckbpmfr qrgj ggklcf tshvcthw ndjm dwjbzk bqrqpvm cjzvt wvm zzmqdsjn txqvfmw nhhqxhtn hffrlx mmlqmsp vcs mkg kkwrmlc blmqbp wlcgtllv hhtkcbb ssbvr wtd jxpg gjqlwj khqsrxv fdwl btsbpt jdcm nxhkpwm tkglcrkt wxvgdmft jfpwfx fnvggl bpvntvq njksb ljgxgmkj zwz nhqvfszp szkddqmz xdpmgnv mzb jthkl rhfqjr qtrq nsvj pwbsrg tlzr chc brk jkg pxft jqzv kmxtmpsj xttmmw zfz dbvm vfs gsqflp jwn hdx tsndr bwhwb nxwsllbh jvrkjqj brnqc qsmjxb srnbvxcx wcnwhmv ndfs ldh gwxtbr rldq fxrgqk tfjjsf nvh whg fglw dgmdh mgrr dxgf jzxrxdp mhkgcsf djkh jnnxqxr hbhm hcstvcg qdbct dzkhvr gnl tnbps txqn jcdfrxw cwbb pswrrt prpz ztjhsdw thcntln tfpw dbpshlp tcwxg pmqgrwfg rqlclhqh pjvjs pwltbjz sqvbj lcm kcl sxzpdgk llqrw jwjscq rgnmttc llxtb flhhzjf mzgc xnnzglt hfcpdf tpsrpxjb mgwxhbp fzrznfg lrmh nrtcgq mxfkbjgg sctwk dszfjv wxszzfzc bvqv ncx cqhf lnq rhbffm vlmnv hfxqxm jkhrk wxxjcn xfvbs rkfl pkbxvq rkw tbqbdp lsprtfvj fvld tjgslm xffktkkf rxtcttn ftqwwz gnl xjv smcfpksz khcxpmdq rcrxp hqvfmhd smdcgxqj vbtknxvw fdlxb khvbh plw zmwbkgf xlwpwl rfqwqhr wngnwp dzlgnlf bwwvvgcs spsjv rlbgrc fwkmhc bvpfbk hplm jppcqgt rjn pjxlktzk ngc phbjz vxnxqq kjmnnhx kqw nkp qzcchxk xggrws dgzgkm xhmcgf jjhjjk nbwwnlzd cwbhhhcz tjfk pfmfgb wpqlh shbpkxpr pskh mhfvc mpqbdd ggnpsnsf qljfrz mtlcfhvg pxwmp mtpmknht bwv wkqj xkh pgfm xwnklnpz rklgjgj chxskvjd tbncmxhp skjqzss chdxk bpk jmw rmh mxgbcsgt dxdnb mmf rmfrdwc vkcpxcs hsd gbw cslscj mkxd mjdrfrht mhnmkvlw xxshrjd csrfl bvv wkx dzjt sgqsbm svhvmssx zxcvr jqmj nrs dcxl lmpf bnnbzfgq hhbf rkhwbx zwm szqndd vpw hwdnfvxf lwxklnmq nqhmhnfs cmdcqqc nhns rhqskfkr xlpjnjrs cql mgzvb tffxx nhzz djgmgn cfwpkbmw xpmxhtp xsxqv fttdfvll lwrdbkrd clmng lhbmd bgrlsq vbshtjz hqvnjc dmhk ljzg mmmfg rhvbg pzxxpm sbvkh rccbphlr jvs tkms wqpszg wtvxs xqnnwzm zppnx wndrv jbpbt jjc pds tdstvpx jprnhkl mmftfckj gjvn nscqskm gkqgwvdn ljkqjhdw lqwxxrbr lhgpk zsvhccdb hcx btpjl xjj pxq dkz hvhxhcpz csclxgl brshhpm qvtz kzmbkdjl pnxrdhjq xcn btpczlnf bfv prbwdncn bzqsq dnszh nlnh xtphddrt pkqxwsz rltrp jcz vzqprzxc lhdscvtk nkhdjc ltrrxh tqqjgbnv hbhnpqvq mrqg sht kzqjjs jwvtrt cxbz rlbhd qjttpsmr psxpzdf zshcm jfhkn bpxt szf mppxdtj wrhj chsr mmll ktjjxp dzd djsc rrdgk tpdcgbh jrxrfdxv ndcj wmqnxf ndqxpkws zddxkjmw xrkclk chpr zdsc xphpg scr mmt pzc gkfxnfnd bhxsb rjhmsnts fxspqnjv sjdkq vlfxn bwcxwgxt dfxsc mftbv vkprh bxhbhkjd lhc ngdqmd cbfbfzq hthhcj xxlff lzvn vcp mmxbvp pjrrvdg wfcqb jqrwvh hxk njb zmm fmnjhvd chmwv fwl wgztjkwd dlv gdxktj zwbhn lgbvtzr lzfgrvw pfqmfj htkv wgcw kbfw rcfxb lkfmsclq mqrn xxhv ckkzbjx cfrpn clg lwx nqkpc hlpjw zfz nlkdls nsnt fzwdtk bvqmwd jvtxnxn pjqbbtk lkzzpl pttrbf gjsn kqm kbqrx zgsmfns"

# Text to be used
text = textB

gdd = GDD.new(text)
puts "#{gdd.find_prepositions.size} prepositions"
puts "#{gdd.find_verbs.size} verbs"
puts "#{gdd.find_first_person_verbs.size} first person verbs"
puts "#{gdd.sort_and_strip_repetitions}"
puts "#{gdd.find_beautiful_numbers.uniq.size} beautiful numbers"
