######################################################################
# Automatically generated by qmake (1.07a) Mon May 17 23:57:20 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += parent_child.cpp
